name: publish
on:
  push:
    branches: [ master ]

jobs:
  #Publish's job
  publishimage:
    name: Publish image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
    uses: docker/login-action@v1
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the App Docker image
        run: |
          docker build . --tag ghcr.io/viajook/doc-project-cicd1:latest
          docker run ghcr.io/viajook/doc-project-cicd1:latest
          docker push ghcr.io/jviajook/doc-project-cicd1:latest
