name: publish
on:
  push:
    branches: [ master ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build the App Docker image
        run: |
          docker build . --tag ghcr.io/viajook/doc-project-cicd1:latest
          docker run ghcr.io/viajook/doc-project-cicd1:latest
          docker push ghcr.io/jviajook/doc-project-cicd1:latest
